addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow

language: python

python:
  - "2.7"

env:
  - VERSION="10.0" ODOO_REPO="osbzr/base" LINT_CHECK="0" PGPASSWORD="travis"


virtualenv:
  system_site_packages: true

install:
  - git clone http://github.com/GoodERPJeff/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - pip install xlrd
  - pip install xlutils
  - pip install docxtpl
  - pip install python-ooxml
  - pip install pdfkit
  - pip install wkhtmltopdf
  - pip install httplib2

script:
  - travis_run_tests

after_success:
  coveralls
